---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Setting up num_users for workshop
  debug:
    msg: "Setting up num_users for workshop num_users = {{ num_users }}"

- name: Setting up module_type for workshop
  debug:
    msg: "Setting up module_type for workshop module_type = {{ module_type }}"

- name: Give access to opentlc-mgr
  shell: |
         oc adm policy add-cluster-role-to-user cluster-admin {{ ocp_username }}

- name: create module list
  set_fact:
    modules: "{{ module_type.split(';') | map('trim') | list }}"

- name: Selected Modules
  debug:
    msg: "selected modules list: {{ modules }}"

- name: Create CCN CatalogSource
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/redhat-operators-index.yaml
  # - ./files/community-operators-index.yaml

- name: create labs-infra project
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "labs-infra"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "Lab Infrastructure"


- name: create inventory and catalog user projects
  when: ("m1" in modules or "m2" in modules or "m3" in modules)
  include_tasks: create_project.yaml
  vars:
    name: "{{ item[0] }}-{{ item[1] }}"
    user: "{{ item[0] }}"
  loop: "{{ users|product(['inventory', 'catalog'])|list }}"



- name: install guides
  include_tasks: install-guides.yaml
  vars:
    guide: "{{ item }}"
  loop: "{{ modules }}"

